apiVersion: stroom.gchq.github.io/v1
kind: DatabaseServer
metadata:
  name: dev
  namespace: stroom
spec:
  image:
    repository: mysql/mysql-server
    tag: 8.0.26
  databaseNames:
    - stroom
    - stats
  additionalConfig: []
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  volumeClaim:
    volumeName: stroom-db
    accessModes:
      - ReadWriteOnce
    storageClassName: ""
    resources:
      requests:
        storage: 200Mi
      limits:
        storage: 500Mi
