apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stroom-operator-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stroom-operator-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stroom-operator-databasebackup-editor-role
rules:
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databasebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databasebackups/finalizers
  verbs:
  - update
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databasebackups/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stroom-operator-databasebackup-viewer-role
rules:
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databasebackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databasebackups/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stroom-operator-databaseserver-editor-role
rules:
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databaseservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databaseservers/finalizers
  verbs:
  - update
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databaseservers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stroom-operator-databaseserver-viewer-role
rules:
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databaseservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databaseservers/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stroom-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databasebackups
  - databaseservers
  - stroomclusters
  - stroomtaskautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databasebackups/finalizers
  - databaseservers/finalizers
  - stroomclusters/finalizers
  - stroomtaskautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databasebackups/status
  - databaseservers/status
  - stroomclusters/status
  - stroomtaskautoscalers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stroom-operator-stroomcluster-editor-role
rules:
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomclusters/finalizers
  verbs:
  - update
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomclusters/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stroom-operator-stroomcluster-viewer-role
rules:
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomclusters/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stroom-operator-stroomtaskautoscaler-editor-role
rules:
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomtaskautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomtaskautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomtaskautoscalers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stroom-operator-stroomtaskautoscaler-viewer-role
rules:
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomtaskautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomtaskautoscalers/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stroom-operator-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stroom-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: stroom-operator-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stroom-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stroom-operator-manager-role
subjects:
- kind: ServiceAccount
  name: stroom-operator-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ include "stroom-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: stroom-operator-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      containers:
      - args:
        - --leader-elect
        - --health-probe-bind-address=:8081
        command:
        - /manager
        image: {{ if .Values.registry }}{{ printf "%s/" .Values.registry }}{{ end }}{{ "gradata/stroom-k8s-operator" }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports: []
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{ toYaml .Values.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts: []
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      securityContext: {{ toYaml .Values.securityContext | nindent 8 }}
      serviceAccountName: stroom-operator-controller-manager
      terminationGracePeriodSeconds: 10
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      volumes: []
