name: Build Helm Chart

on:
  push:
    branches: [master]
  pull_request: 

jobs:    
    build_helm_chart:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Helm
        uses: azure/setup-helm@v3.3
        with:
          version: v3.9.0
      - name: Build stroom-operator-crds chart
        run: |
          helm package ./charts/stroom-operator-crds

      - name: Build stroom-operator chart
        run: |
          helm package ./charts/stroom-operator